### ISSUE TITLE
Not working for files that contains dot in file name

### ISSUE THREAD

**Issue by eMuonTau** [joostlubach/js-index#8]
Do you have any plan to merge #1. It's been more than 2 years.
Angular and NestJS uses `.` in file names by convention eg: `order.service.ts`. js-index produces incorrect output for these files.

**Current Behaviour:**
```typescript
export * from "./order";
```

**Expected Behevior:**
```typescript
export * from "./order.service";
```

**Comment by joostlubach** [comment]
This is now published. Thank you!
